mmpi/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import *


app_name = 'mmpi'
urlpatterns = [
    path('', TemplateView.as_view(template_name='mmpi/main.html'), name='main'),
    path('male_test/', MaleTest.as_view(), name='male_test'),
    path('female_test/', FemaleTest.as_view(), name='female_test'),
    path('results/<pk>', Results.as_view(), name='results'),
    path('more', TemplateView.as_view(template_name='mmpi/more.html'), name='more')
]

mmpi_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mmpi.urls')),
]

mmpi/models.py
from django.db import models


class MaleQuestion(models.Model):
    text = models.CharField('Текст вопроса', max_length=300)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы (женская версия)'


class FemaleQuestion(models.Model):
    text = models.CharField('Текст вопроса', max_length=300)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы (женская версия)'


class AverageData(models.Model):
    scale = models.CharField('Шкала', max_length=100)
    yes = models.JSONField('Ответы "да"', blank=True)
    no = models.JSONField('Ответы "Нет"', blank=True)
    m_male = models.FloatField('Мужчины M')
    sigma_male = models.FloatField('Мужчины  δ')
    m_female = models.FloatField('Женщины M')
    sigma_female = models.FloatField('Женщины  δ')
    description = models.TextField('Описание', max_length=1000, default='', blank=True)

    def __str__(self):
        return self.scale

    class Meta:
        verbose_name = 'Расшифровка вопроса'
        verbose_name_plural = 'Расшифровка вопросов'


class ResultsData(models.Model):
    id = models.UUIDField('Идентификатор', primary_key=True)
    main_scales = models.JSONField('Основные шкалы')
    additional_scales = models.JSONField('Дополнительные шкалы')

    class Meta:
        verbose_name = 'Результаты'
        verbose_name_plural = 'Результаты'

mmpi/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from uuid import uuid1
from .models import *
import json


class MaleTest(View):
    def get(self, request):
        request.session['sex'] = 'male'
        return render(request, 'mmpi/test.html', {'questions': MaleQuestion.objects.all(), 'uuid': uuid1()})


class FemaleTest(View):
    def get(self, request):
        request.session['sex'] = 'female'
        return render(request, 'mmpi/test.html', {'questions': FemaleQuestion.objects.all(), 'uuid': uuid1()})


class Results(View):

    def get(self, request, pk):
        try:
            results = get_object_or_404(ResultsData, id=pk)
            main_scales = results.main_scales
            additional_scales = results.additional_scales
        except:
            return render(request, 'mmpi/results.html', context={'error': True})
        else:
            return render(request, 'mmpi/results.html',
                          context={'values': list(main_scales.values()), 'keys': list(main_scales.keys()),
                                   'add_scales': additional_scales.items(), 'uuid': pk, 'clearLS': 'true'})

    def post(self, request, pk):

        def raw_score_calculation(datas):
            results = {}
            for data in datas:
                results |= {data.scale: 0}
                for i in range(1, 567):
                    if (i in data.yes and request.POST[f'answer{i}'] == 'yes') or (
                            i in data.no and request.POST[f'answer{i}'] == 'no'):
                        results[data.scale] += 1
            return results

        def t_score_calculation(results):
            for key in results.keys():
                scale = AverageData.objects.get(scale=key)
                if request.session['sex'] == 'male':
                    results[key] = round(50 + 10 * (results[key] - scale.m_male) / scale.sigma_male, 1)
                else:
                    results[key] = round(50 + 10 * (results[key] - scale.m_female) / scale.sigma_female, 1)

        main_scales = raw_score_calculation(AverageData.objects.filter(id__lte=14))
        additional_scales = raw_score_calculation(AverageData.objects.filter(id__gt=14))

        main_scales['9'] += main_scales['K'] * 0.2
        main_scales['4'] += main_scales['K'] * 0.4
        main_scales['1'] += main_scales['K'] * 0.5
        main_scales['7'] += main_scales['K'] * 1
        main_scales['8'] += main_scales['K'] * 1

        if request.session['sex'] == 'male':
            main_scales.pop('5(Ж)')
            additional_scales.pop('Ригидность (женская)')
            additional_scales.pop('Стабильность профиля (женская)')
        elif request.session['sex'] == 'female':
            main_scales.pop('5(М)')
            additional_scales.pop('Ригидность (мужская)')
            additional_scales.pop('Стабильность профиля (мужская)')

        t_score_calculation(main_scales)
        t_score_calculation(additional_scales)

        ResultsData(id=pk, main_scales=main_scales, additional_scales=additional_scales).save()

        return render(request, 'mmpi/results.html',
                      context={'values': list(main_scales.values()), 'keys': list(main_scales.keys()),
                               'add_scales': additional_scales.items(), 'uuid': pk, 'clearLS': 'true'})

mmpi/templates/mmpi/main.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'mmpi/main_style.css' %}">
    <title>Тест СМИЛ</title>
</head>
<body>
    <div class="description">
        <h1 class="description_header">Тест СМИЛ</h1>
        <p class="description_p">Стандартизированный метод исследования личности (СМИЛ) – адаптация теста MMPI, сделанная Людмилой Николаевной Собчик.
            СМИЛ не имеет клинической направленности и основывается на индивидуально-типологическом подходе автора.</p>
        <p class="description_p">В тесте 566 вопросов, среди которых есть вопросы для проверки достоверности полученных результатов, старайтесь отвечать искренне.
            Тест выявляет показатели по всем основным и дополнительным шкалам и формирует из них график.
            Также представлены материалы для интерпретации результатов.</p>
        <p class="description_p">Если вы случайно перезугрузили или закрыли страницу с тестом,
            попробуйте просто зайти снова. Скорее всего, имеющиеся ответы сохранятся.</p>
    </div>

    <div class="test">
        Начать тестирование:
        <a class="test_url" href="{% url 'mmpi:male_test' %}">Мужская версия</a>
        <a class="test_url" href="{% url 'mmpi:female_test' %}">Женская версия</a>
    </div>

    <div class="more">
        Информация о тесте (методичка):
        <a class="more_url" href="{% url 'mmpi:more' %}">Подробная интерпретация</a>
    </div>

    <div class="example">
        <a class="example_url" href="{% url 'mmpi:results' '3f0c0c66-540d-11ee-ae82-f8a2d6486ed3' %}">Пример результатов</a>
    </div>
</body>
</html>

mmpi/templates/mmpi/results.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Тест СМИЛ: результаты</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/broken-axis.js"></script>
    <link rel="stylesheet" href="{% static 'mmpi/results_style.css' %}">
</head>
<body>
    {% if error %}
        <h2>Результатов по данной ссылке не существует</h2>
    {% else %}
        <div class="profile">
            <p class="profile_sign">Сохранить результаты можно в этом меню:</p>
            <div class="profile_chart" id="profile"></div>
        </div>

        <table class="main-scales_table">
            <tr> <th>Шкала</th> <th>Результат</th> <th>Описание</th> </tr>
            <tr> <td>L</td> <td>{{ values.0 }}</td> <td>Шкала L (лжи) служит для оценки искренности ответов испытуемого. Высокие показатели выявляют ложные ответы.</td> </tr>
            <tr> <td>F</td> <td>{{ values.1 }}</td> <td>Шкала F служит для оценки достоверности, надежности получаемых результатов. При выкоких результатах тенденция к драматизации сложившихся обстоятельств.</td> </tr>
            <tr> <td>K</td> <td>{{ values.2 }}</td> <td>Шкала K (коррекции) служит для компенсации защитных реакций испытуемого путем коррекции получаемых «сырых баллов». При выкоких результатах тенденция отрицать проблемы.</td> </tr>
            <tr> <td>1</td> <td>{{ values.3 }}</td> <td>Шкала невротического сверхконтроля (ипохондрии) xарактеризует защитные гиперкомпенсационные реакции испытуемого, озабоченность своим здоровьем.</td> </tr>
            <tr> <td>2</td> <td>{{ values.4 }}</td> <td>Шкала пассивности (депрессии) характеризует поведение личности в условиях стрессогенных факторов, пессимистичность, упадок сил, пассивность, самокритичность.</td> </tr>
            <tr> <td>3</td> <td>{{ values.5 }}</td> <td>Шкала лабильности (демонстративности, истерии) характеризует стремление быть в центре внимания, эффектность поведения, поверхностность в контактах и чувствах.</td> </tr>
            <tr> <td>4</td> <td>{{ values.6 }}</td> <td>Шкала импульсивности (психопатии) характеризует раскованность, спонтанность поведения, агрессию, импульсивность.</td> </tr>
            <tr> <td>5</td> <td>{{ values.7 }}</td> <td>Шкала мужественности – женственности определяет преобладание черт стереотипно-мужского (в женском профиле) либо стереотипно-женского (в мужском профиле) поведения в отношениях с окружением.</td> </tr>
            <tr> <td>6</td> <td>{{ values.8 }}</td> <td>Шкала регидности (паранои) характеризует категоричность, подозрительность, уверенность в личных идеях, установках.</td> </tr>
            <tr> <td>7</td> <td>{{ values.9 }}</td> <td>Шкала тревожности (психостении) устанавливает степень выраженности тревоги личностной или ситуативной.</td> </tr>
            <tr> <td>8</td> <td>{{ values.10 }}</td> <td>Шкала индивидуалистичности (шизоидности, шизофрении) отражает степень выраженности индивидуального в высказываниях и адаптации, эксцентричность, независимость мышления, отстранённость.</td> </tr>
            <tr> <td>9</td> <td>{{ values.11 }}</td> <td>Шкала оптимизма (гиппомании) отражает энергетический потенциал и общий жизненный тонус личности.</td> </tr>
            <tr> <td>0</td> <td>{{ values.12 }}</td> <td>Шкала интроверсии – экстраверсии определяет степень отстранённости от социальной среды, закрытость, застенчивость.</td> </tr>
        </table>

        <details class="additional-scales">
            <summary class="additional-scales_summary">Дополнительные шкалы</summary>
            <table class="additional-scales_table">
                <tr> <th>Шкала</th> <th>Результат</th> </tr>
                {% for scale in add_scales %}
                    <tr> <td>{{ scale.0 }}</td> <td>{{ scale.1 }}</td> </tr>
                {% endfor %}
            </table>
        </details>


        <p>Разброс показателей в пределах от 30 до 70 баллов определяет коридор нормы, показатели выше 70 или ниже 30 расцениваются как отклонение от нормы.
            Однако правильнее рассматривать шкалы относительно друг друга, особенно при общем повышении или понижении шкал профиля.
            Повышенные показатели определяют акцентуацию (заострённость) определённых личностных черт, в первую очередь личность характеризуют самые высокие шкалы.
            Первые 3 шкалы призваны оценить достоверность результатов, показатели по L и K выше 70, а также по F выше 80 выявляют недостоверные результаты.</p>

        <p>Ваши результаты сохранены по данной ссылке: <a id="current-page" href=""></a></p>
        <a class="url" href="{% url 'mmpi:more' %}" target="_blank">Подробная интерпретация</a>
        <a class="url" href="{% url 'mmpi:main' %}" target="_blank">На главную</a>

        <script type="text/javascript">

            {% autoescape off %}
                const keys = {{ keys }};
                const values = {{ values }};
                const uuid = '{{ uuid }}';
                const clearLS = {{ clearLS }};
            {% endautoescape %}
            keys[7] = '5';

            var currentPage = document.getElementById('current-page');
            currentPage.href = currentPage.text = window.location.href;

            if (clearLS)
                localStorage.removeItem('answers');

            Highcharts.chart('profile', {

                title: {
                    text: 'Ваши результаты',
                },

                yAxis: {
                    title: false,
                    tickPositions: [0, 10, 20, 30, 40, 50, 60, 70, 80,
                    90, 100, 110, 120, 130, 140, 150, 160, 170, 180]
                },

                xAxis: {
                    categories: [...keys.slice(0, 3), ...[''], ...keys.slice(3, 13)]
                },

                series: [{
                    name: 'Результат',
                    data: [...values.slice(0, 3), ...[null], ...values.slice(3, 13)]
                }],

                legend: {
                    enabled: false
                },

                credits: {
                    enabled: false
                },

                exporting: {
                    filename: `smil_test_${uuid}`
                }
            });
        </script>
    {% endif %}
</body>
</html>

mmpi/templates/mmpi/test.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Тест СМИЛ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'mmpi/test_style.css' %}">
</head>
<body>
    <form method="post" action="{% url 'mmpi:results' uuid %}">
        {% csrf_token %}
        <ul class="questions">
            {% for question in questions %}
                <li class="questions_item" id="question{{ forloop.counter }}">
                    {{ question.id }}. {{ question.text }}<br>
                    <input class="questions_item_radio" type="radio" name="answer{{ forloop.counter }}"
                           id="yes{{ forloop.counter }}" value="yes" required>
                    <label for="yes{{ forloop.counter }}">Да</label>
                    <input class="questions_item_radio" type="radio" name="answer{{ forloop.counter }}"
                           id="no{{ forloop.counter }}" value="no" required>
                    <label for="no{{ forloop.counter }}">Нет</label>
                </li>
            {% endfor %}
        </ul>
        <input class="complete" type="submit" name="complete" value="Завершить">
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function() {

            document.querySelector('.complete').addEventListener('click', function () {
                document.querySelectorAll('.questions_item').forEach((item) => {
                    var options = item.querySelectorAll('.questions_item_radio');
                    if (!options[0].checked && !options[1].checked)
                        item.scrollIntoView({behavior: 'smooth'});
                });
            });

			var savedAnswers = JSON.parse(localStorage.getItem('answers'));
			if (savedAnswers)
				Object.entries(savedAnswers).forEach((item) => {
					document.querySelector(`#${item[1]}${item[0].slice(8)}`).checked = true;
				});

			document.querySelectorAll('.questions_item').forEach((item) => {
				item.addEventListener('change', function() {
					var answers = JSON.parse(localStorage.getItem('answers'));
					if (!answers)
						answers = {};

					var options = item.querySelectorAll('.questions_item_radio');
					if (options[0].checked)
						answers[item.id] = 'yes';
					else if (options[1].checked)
						answers[item.id] = 'no';

					localStorage.setItem('answers', JSON.stringify(answers));
				});
            });
        });
    </script>
</body>
</html>